# Generated by Django 3.0.4 on 2020-03-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='people_watching',
            new_name='users_watching',
        ),
    ]
