# Generated by Django 3.0.4 on 2020-03-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200324_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_friend_of',
            field=models.ManyToManyField(related_name='_user_is_friend_of_+', to='app.User'),
        ),
    ]
