# Generated by Django 3.0.4 on 2020-03-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_user_is_friend_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_friend_of',
        ),
        migrations.AddField(
            model_name='user',
            name='external_friends',
            field=models.ManyToManyField(related_name='_user_external_friends_+', to='app.User'),
        ),
    ]
