# Generated by Django 3.0.4 on 2020-03-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200324_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='external_friends',
        ),
    ]
