# Generated by Django 3.0.4 on 2020-03-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200326_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tokens',
            field=models.TextField(default='[]', max_length=100000),
        ),
    ]
