# Generated by Django 3.0.4 on 2020-03-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_user_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(default='https://robohash.org/anonymous/?set=set4&size=1000x1000'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='preview_avatar',
            field=models.URLField(default='https://robohash.org/anonymous/?set=set4&size=350x350'),
        ),
    ]
